### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by alenrajsp** [firefly-cpp/smart-agriculture-datasets#5]
I would suggest the following tags so that visibility of this repository is improved.

[smart-agriculture](https://github.com/search?q=smart+agriculture) [agriculture](https://github.com/topics/agriculture) [smartfarm](https://github.com/topics/smartfarm) [smart-farming](https://github.com/topics/smart-farming)

Add any other tags you find applicable :)

**Comment by firefly-cpp** [comment]
Done. Thanks.
